name: Quire
on:
  push:
    branches:
      - master
permissions:
  actions: read
  checks: read
  contents: write
  deployments: write
  pull-requests: write
  repository-projects: write
  statuses: write
jobs:
  quire-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Git init
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "gihubaction@users.noreply.github.com"
      - name: Quire install
        run: |
          sudo npm install --global @thegetty/quire-cli@1.0.0-rc.11
      - name: Quire build
        run: quire build
      - name: GH Pages customizations
        run: |
          rm -rf docs || echo "not removing docs"
          mv _site docs
          touch docs/.nojekyll
          touch docs/_assets/.nojekyll
          test -d docs/static || mkdir docs/static
          echo "${PUBLIC_URL}" > docs/static/CNAME
          echo "${PUBLIC_URL}" > docs/CNAME
        env:
          PUBLIC_URL: ${{ vars.PUBLIC_URL }}
      - name: Git push back
        run: |
          git add docs || echo "INFO - nothing to add"
          git commit -m "Quire: publishing assets" || echo "INFO - nothing to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
